### PR TITLE
Add ColdFront 2019

### PR DESCRIPTION
**Pull request by auchenberg**

### CODE REVIEW

**Comment by frontendfront** [comment]
The url is not working. I think it's `.co`

**Comment by auchenberg** [comment]
@frontendfront Fixed.

**Comment by cgrail** [comment]
@auchenberg I've also added it to our conference list: https://github.com/tech-conferences/conference-data/pull/817

**Comment by auchenberg** [comment]
@cgrail Ah cool, thanks!

**Pull request merged**
