### PR TITLE
Updated Frontend United date

### PR DESCRIPTION
**Pull request by pjbaert**
The conference is spread over 2 days.

### CODE REVIEW

**Comment by pjbaert** [comment]
See http://frontendunited.org/ as verification

**Comment by frontendfront** [comment]
Please also add the http in front of the url because it doesn't link right. I've been meaning to do it myself but I keep forgetting.

**Comment by pjbaert** [comment]
Added the http:// in front of the url.

**Comment by frontendfront** [comment]
Awesome!

**Pull request merged**
