### PR TITLE
Add MFE2024 to listing

### PR DESCRIPTION
**Pull request by JamieBradders**
I am raising this PR to add [Middlesbrough Front End](https://middlesbroughfe.co.uk) Conference to the listings.

It looks like my VS Code auto-formatter has removed some whitespace from the file, hence the large additions count. But no other content has been modified. I assumed this would be okay, but please let me know if this is a cause for concern.

Thanks!

### CODE REVIEW

**Comment by JamieBradders** [comment]
Hey 👋 - just wanted to see if anyone was able to check this PR? Thank you 🙏

**Comment by frontendfront** [comment]
Please don’t remove the trailing whitespaces. They are needed in Github Markdown for line breaks.

**Comment by JamieBradders** [comment]
Okay thank you, I'll fix this :)

**Comment by JamieBradders** [comment]
> Please don’t remove the trailing whitespaces. They are needed in Github Markdown for line breaks.

Hey 👋 I've resolved this as requested, please can you re-review?

**Pull request merged**
